### ISSUE TITLE
more chocolate milk!

### ISSUE THREAD

**Issue by RIPISDRAD** [Mooy1/SimpleUtils#1]
hey there
1-you create 4 bottle of milk with glass of bottle and 1 bukkit of milk
2-you combine them with 4 coco beans
3-now you have 8 bottles of chocolate milk + 4 empty milk bottles
so this is urs (i already report it to them and this is becoming urs kinda) because if i put
the coco beans + empty milk bottle in simple workbench becomes 2 more of chocolate milk!

**Comment by Riley31415** [comment]
my table takes sf recipes and vanilla recipes, so they need to fix
