### ISSUE TITLE
Simple Elevator not decending below y=1

### ISSUE THREAD

**Issue by marvjosh1** [Mooy1/SimpleUtils#10]
## Description (Required)
When using the simple elevator, you cannot decend to those that are at a negative y level

## Steps to reproduce the Issue (Required)
Place two simple evevators above each other, one at positive y coordinates and one at negative y coordinates
https://www.youtube.com/watch?v=JsMPJTnvDzs

## Expected behavior (Required)
For the elevator to function normally and teleport the player down

## Environment (Required)
https://i.imgur.com/a2FIEk6.png
https://i.imgur.com/jwa99IE.png

**Comment by Boomer-1** [comment]
it's not a bug, just a feature that hasn't been added yet

**Comment by Riley31415** [comment]
ill fix this, its probably cause i coded it before 1.17
