### ISSUE TITLE
SimpleWorkbench seems to bypass a lot of checks that normal Workbenches have

### ISSUE THREAD

**Issue by Skizzles** [Mooy1/SimpleUtils#3]
## Description (Required)

When testing the SimpleWorkbench it bypasses other plugins checks.

Jetsminions the item for a minion is a nether star and the normal crafting table does not allow it to be crafted while the simpleworkbench does. 

SuperiorSkyblock there are missions that check if an item is crafted in the crafting table, these don't work with the simpleworkbench.

WildChests have custom chests that can be created, I have these setup with SF items and normal items, however the SimpleWorkbench seems to not work on recipes containing both SF items and vanilla ones.

It seems the simpleworkbench is missing normal checks that a workbench has.

## Steps to reproduce the Issue (Required)

https://screenshots.skizzles.me/wAnA3/NugUjUNe75.mp4
https://screenshots.skizzles.me/wAnA3/QiwAYIba73.mp4
## Expected behavior (Required)

In my opinion this should work like a standard workbench but I understand if this is not possible. Depends on what you consider things that can be fixed :)

## Server Log / Error Report

No errors

## Environment (Required)

https://screenshots.skizzles.me/wAnA3/hANIWiCu80.png

**Comment by Riley31415** [comment]
I will look into the events that are fired normally, thanks for letting me know

**Comment by Riley31415** [comment]
Are you adding the recipes for the wild chests in the wild chest config? I can't seem to find where they are registering recipes.

**Comment by Skizzles** [comment]
> Are you adding the recipes for the wild chests in the wild chest config? I can't seem to find where they are registering recipes.

I register them through another plugin since wild chests does not have custom recipe support. I use https://www.spigotmc.org/resources/1-9-1-16-custom-recipes-and-crafting-craftenhance.65058/

since other plugins don't allow registering NBT data (which sf items require)

**Comment by Riley31415** [comment]
So ive done a bit of testing, I cant use the events that those plugins are using to cancel the crafting since I'm using a custom inv. I'm still trying to figure out why your custom recipe thing wouldn't work

**Comment by Skizzles** [comment]
Fully understood, If you need any details from me then feel free to ask!

**Comment by SecretarySami** [comment]
> So ive done a bit of testing, I cant use the events that those plugins are using to cancel the crafting since I'm using a custom inv. I'm still trying to figure out why your custom recipe thing wouldn't work

Is there any update on this by chance ?

**Comment by Riley31415** [comment]
Ill have a look over the code again but i dont think ill be able to allow cancelling of the craft by other plugins.

**Comment by SecretarySami** [comment]
I appreciate you trying

**Comment by Skizzles** [comment]
we resolved this by switching to another plugin
