### ISSUE TITLE
SimpleSieve is not sieving gravel into dusts

### ISSUE THREAD

**Issue by Leonard456** [Mooy1/SimpleUtils#4]
## Description (Required)
Simple sieve is not working after i sieve gravel the dusts is not coming into output chest and after i destroy output chest is not coming to inventory

## Expected behavior (Required)
I expected this:After i sieve gravel dusts will come into output chest or inventory

## Server Log / Error Report
[20:45:19 ERROR]: [SimpleUtils] Item "SIMPLE_SIEVE" from SimpleUtils vDEV - 5 (git 8d51c591) has caused an Error!
[20:45:19 ERROR]: [SimpleUtils] You can report it here: https://github.com/Mooy1/SimpleUtils/issues
[20:45:19 ERROR]: [SimpleUtils] Could not pass "MultiBlockInteractionHandler" for Sieve - 'SIMPLE_SIEVE' (SimpleUtils vDEV - 5 (git 8d51c591))

## Environment (Required)
![Snímka](https://user-images.githubusercontent.com/83669068/117055570-97f3ed80-ad1b-11eb-9223-82a583701206.PNG)

 - Minecraft Version:1.16.5
 - CS-CoreLib Version:1.6.3
 - Slimefun Version:899
 - Plugin Version: 5

**Comment by Riley31415** [comment]
Can you post the full logs in pastebin? Also, you dont need CS-CoreLib anymore

**Comment by Riley31415** [comment]
Nevermind, ive got a fix for next build

**Comment by Leonard456** [comment]
Thank you

**Comment by Leonard456** [comment]
When will the update be?

**Comment by Riley31415** [comment]
When i get around to testing it, hopefully this weekend

**Comment by Leonard456** [comment]
Thank you
