### ISSUE TITLE
kinda free xp

### ISSUE THREAD

**Issue by RIPISDRAD** [Mooy1/SimpleUtils#5]
1-hey there long time
when u try to make sth specially with simpleutil  it doesnt consider that u unlock it or not (try this it is simple u can put a bucket of milk in there and heavy cream is ready or just try the knockback stick)

2- the second issue is like is doesnt take durability as a factor like u must put an unuse flint but as i said it doesnt take durablity a factor so it builds it

**Comment by Riley31415** [comment]
Ill fix the first one, for the 2nd one it would be difficult and reduce the speed/performance
