### ISSUE TITLE
Disappearing content of backpack

### ISSUE THREAD

**Issue by EpicPlayerA10** [Mooy1/SimpleUtils#6]
## Description (Required)
When you try to upgrade your backpack in Simple Workbench, backpack content will be deleted.

## Steps to reproduce the Issue (Required)
https://youtu.be/BHkUfGrpjxA

## Expected behavior (Required)
It should save content of the backpack

## Server Log / Error Report
not relevant

## Environment (Required)
![obraz](https://user-images.githubusercontent.com/62206933/130597540-6ba00ec9-fd52-4a0b-9eaa-df7e538830ba.png)

**Comment by Riley31415** [comment]
In the next build it will prevent you from crafting backpacks, you will need to use enhanced crafting table.
