### ISSUE TITLE
Crafted Item Dissapears when Inventory is full

### ISSUE THREAD

**Issue by alfonsusac** [Mooy1/SimpleUtils#7]
## Description (Required)
The item dissapears then trying to craft an item while the inventory is full. I have tested this on simple workbench.

## Steps to reproduce the Issue (Required)
1. Fill your inventory
2. Put simple workbench
3. Put down recipe
4. Craft

## Expected behavior (Required)
Item is dropped to the ground or atleast declines the crafting by saying that the players inventory is full.

## Server Log / Error Report
No error report

## Environment (Required)
 - Minecraft Version: 1.17.1
 - CS-CoreLib Version: none
 - Slimefun Version: 966
 - Plugin Version: vDev - 12

**Comment by Riley31415** [comment]
It should drop to the ground, it does in my tests, can you send a video? It could be another plugin affecting it.
