### ISSUE TITLE
Simple Workbench doesnt work with Exotic Garden

### ISSUE THREAD

**Issue by alfonsusac** [Mooy1/SimpleUtils#8]
## Description (Required)
Crafting any kind of essence recipes of exotic garden will always give 2 dirt instead of their respective materials. For example, 8 diamond_essence gives 2 dirt, 8 coal_essence gives 2 dirt, and et cetera.

## Steps to reproduce the Issue (Required)
1. Put down simple work bench
2. Put recipes of essence of exotic garden 

## Expected behavior (Required)
Gives their respectives material 8 diamond essence = 1 diamond, etc
 
![image](https://user-images.githubusercontent.com/20208219/132498875-bc02e446-b0ab-49d4-8c12-09a08f44e61a.png)

 
## Server Log / Error Report
No server log

## Environment (Required)
 - Minecraft Version: 1.17.1
 - CS-CoreLib Version: none
 - Slimefun Version: 966
 - Plugin Version: vDev - 12

**Comment by Riley31415** [comment]
Fixed in new build, reopen if it doesnt work
